# Origine du code : Code généré par Symfony et conservé sans modification fonctionnelle, hors commentaire de traçabilité.
framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        providers:
